### ISSUE TITLE
Impossible to test @opentok/client

### ISSUE THREAD

**Issue by Draichi** [opentok/opentok-web-samples#100]
I'm using a Vue.js app and I adapted the codes from  `opentok-web-samples/Archiving` to run in a SPA.

The problem is when I wrote the script to test, using Jest, I receive a very mysterious message right in the import:

```sh
TypeError: Cannot read property 'getAttribute' of undefined

      20 | 
      21 | <script>
    > 22 | import OT from "@opentok/client";

```

So I tried to mock the whole opentok/client module, the same mysterious error message appears:
```sh
TypeError: Cannot read property 'getAttribute' of undefined

    > 1 | const OT = jest.genMockFromModule('@opentok/client')

```

What can I do here?
I'd appreciate a more supportive documentation for modern JS frameworks too :grimacing:

PS: I'm using the paid version

**Comment by pjchender** [comment]
Looks like there is still no idea?

**Comment by Draichi** [comment]
@pjchender I had to do the following:

create a `__mocks__/@opentok/client.js` file right next to node_modules folder:
```
|-- node_modules
|-- __mocks__
    |-- @opentok
        |-- -client.js
```

client.js:

```js
const OT = {
  initSession: function () {
    const obj = {
      on: function() {
        return
      },
      connect: function() {
        return
      }
    }
    return obj
  }
}



export default OT
```

**Comment by pjchender** [comment]
@Draichi Thanks, this is really helpful.

**Comment by sbjovanovski** [comment]
@pjchender thanks for the example give, very useful, but now I am getting this error 
```
TypeError: _this2.state.publisher[key] is not a function
```
any idea how to fix this?

**Comment by anschwa** [comment]
This would be great if the opentok client library could fix this.
