### ISSUE TITLE
Invalid state transition: Event 'disconnect' not possible in state 'disconnected'

### ISSUE THREAD

**Issue by Noido** [opentok/opentok-web-samples#101]
Hi I try use session.disconnect() for disconnect clients and i got this error

Invalid state transition: Event 'disconnect' not possible in state 'disconnected'

My session is already connect so i dont understand 

@msach22 ?

Thanks

**Comment by msach22** [comment]
@Noido Hmm, are you listening for the `sessionDisconnected` event? Can you confirm that you're calling `session.disconnect` and have not received the event before?

**Comment by Noido** [comment]
yes sessionDisconnected 

I have a function 

```
function ready(fn) {
        if (document.readyState != 'loading'){
            fn();
        } else {
            document.addEventListener('DOMContentLoaded', fn);
        }
    }
 ready(function() {
  connectToSession();
    });

   function connectToSession() {
        session = OT.initSession(apiKey, sessionId);
        session.connect(token, function(err) {
            if (err) {
                console.error(err.message);
                return alert('An error occurred while connecting to the OpenTok session');
            }
            isSessionConnected = true;
        });
    }

```
And i add a btn for disconnect but when i click i got this msg 

```
$('#disconnect').on('click',function(e){
        e.preventDefault();
        if(isSessionConnected == true){
            session.disconnect();
        }

    });
```

But got this error i dont understand why

**Comment by msach22** [comment]
@Noido You're basing the disconnect method off of your flag. Please listen to the session disconnected event by doing the following to toggle your state:

```
session.on({
  sessionDisconnected: event => {
    isSessionConnected = false;
  },
});

**Comment by Nasmar** [comment]
I have the same issue; sessionDisconnected does not seem to do the job for my application. Working in openTok @2.16.0.

**Comment by davideberlein** [comment]
We have the same issue with sdk v
You can see that we are calling session.disconnect() first, then we get the sessionDisconnected event, and then we get the invalid state transition.
![image](https://user-images.githubusercontent.com/3438183/70619097-969cbf00-1c14-11ea-9bce-6a601510403d.png)

**Comment by Nasmar** [comment]
It helped me doing all the following, when wanting to disconnect:
session.off();
session.disconnect();
session.unpublish(publisher, handleError)
publisher.destroy();
session.unsubscribe(subscriber);

But only run those when isSessionConnected to avoid further errors.

**Comment by msach22** [comment]
@davideberlein Can you please share your flow for this error?

**Comment by davideberlein** [comment]
@msach22 this is the code ending a session:
``` javascript
function endSession() {
    // an observable that resolves synchrounusly and holds the Session object returned by `OT.initSession()`
    this.session$.take(1).subscribe(
        session => {
            session.off();
            session.disconnect();
        },
        e => $_tk.log_message("Error disconnectiong session"));

    // an observable that resolves synchrounusly and holds the Publisher object returned by `OT.initPublisher()`
    this.publisher$.take(1).subscribe(
        publisher => apublisher.destroy(),
        e => $_tk.log_message("Error destroying publisher"));
}
```

**Comment by duprez** [comment]
Any updates on this issue?

**Comment by davideberlein** [comment]
@duprez I'm still waiting for an answer from @msach22 or anyone else from opentok

**Comment by mmubasher** [comment]
I am facing this issue still and even support is acting dumb at Vonage. Need a fix for this asap. Thanks
@msach22

**Comment by SardukarSilver** [comment]
Same here( Pls fix it @msach22

**Comment by mmubasher** [comment]
As a last resort, we had to switch to the browser based sdk. It seems the issues exists in NPM package only

**Comment by danilrafiqi** [comment]
i get same issue, when using forceDisconnect(param)

**Comment by bryandowning** [comment]
I got this working by manually unsubscribing each subscriber before disconnecting the session:

```
  const disconnectSession = useCallback(() => {
    if (tokboxSession) {
      tokboxStreams.forEach((stream) => {
        const subscribers = tokboxSession.getSubscribersForStream(stream);
        subscribers.forEach((subscriber) => tokboxSession.unsubscribe(subscriber));
      });
      tokboxSession.disconnect();
    }
  }, [tokboxStreams, tokboxSession]);
```

**Comment by sunilmanipara** [comment]
I think it may be help!

`    
     if (session.currentState === 'connected') {
        session.off();
        session.disconnect();
        session.destroy();
        session.unpublish(publisher);
        publisher.destroy();
        session.unsubscribe('subscriber');
     }
     `
