### ISSUE TITLE
Cannot read property 'WebSocket' of undefined with angular 8

### ISSUE THREAD

**Issue by imranqau5373** [opentok/opentok-web-samples#102]
I am getting this error. when i try to create the object of opentok package. this package is working fine with sample app. but not working with angular 8. i have the same package in both angular versions. i have installed that WebSocket package as well but it is not working. gload object in opentok.js getting undefined.

**Comment by imranqau5373** [comment]
I have fixed this issue. explicitly added the window object in opentok.js.

**Comment by Stefjs** [comment]
Had the same problem
`var global = (function() { return window.global; })();`

**Comment by imranqau5373** [comment]
var global = (function() { return window; })();
this code is working for me. not above one.

**Comment by mmubasher** [comment]
This should be added in polyfills.ts in angular application 
```
(window as any).global = window;
```

**Comment by AskJag07** [comment]
Where do I add the window object in the opentok.js file?
