### ISSUE TITLE
publisher.cycleVideo is not a function

### ISSUE THREAD

**Issue by thereverendruby** [opentok/opentok-web-samples#104]
How can I create a button on my view to call publisher.cycleVideo

html: input type="button" value="Switch Cameras" onclick="toggleCamera();"
js appended at the bottom of app.js from the example code.

function toggleCamera() {
  publisher.cycleVideo().catch(console.error);
}
but I get an error: 
Uncaught TypeError: publisher.cycleVideo is not a function
  
I'm sure I'm missing something simple, thx in advance.

**Comment by msach22** [comment]
@thereverendruby Can you please share what version of OpenTok.js you're using? Can you share how you're instantiating a publisher?

**Comment by thereverendruby** [comment]
We're using the latest version: via: https://static.opentok.com/v2/js/opentok.min.js
Basically we're using it to remote support a customer to see what they're looking at through their phone... here's the js to instantiate the publisher:

/* global OT API_KEY TOKEN SESSION_ID SAMPLE_SERVER_BASE_URL */

var apiKey;
var sessionId;
var token;

function handleError(error) {
  if (error) {
    console.error(error);
  }
}



function initializeSession() {
  var session = OT.initSession(apiKey, sessionId);
  // initialize the publisher
  var publisherOptions = {
    insertMode: 'append',
    width: '100%',
    height: '100%',
    facingMode: "environment",
    audioVolume: 0,
    buttonDisplayMode: 'off',
    mirror: false
  }  
  var publisher = OT.initPublisher('publisher', publisherOptions, handleError);
  // Connect to the session
  session.connect(token, function callback(error) {
    if (error) {
      handleError(error);
    } else {
      // If the connection is successful, publish the publisher to the session
      session.publish(publisher, handleError);
      // publisher.cycleVideo();
    }
  });

}

function toggleCamera() {
  publisher.cycleVideo().catch(console.error);
}

// See the config.js file.
fetch(SAMPLE_SERVER_BASE_URL + '/vsession').then(function fetch(res) {
  return res.json();
}).then(function fetchJson(json) {
  apiKey = json.apiKey;
  sessionId = json.sessionId;
  token = json.token;
  initializeSession();
}).catch(function catchErr(error) {
  handleError(error);
  alert('Failed to get opentok sessionId and token. Make sure you have updated the config.js file.');
});

**Comment by thereverendruby** [comment]
In low light situations since we cannot access the flash/torch we'd like to toggle the camera to the front and show a white screen to light the dark areas. In a nutshell.

**Comment by thereverendruby** [comment]
If we could toggle the flash/torch that would be ideal, but as a workaround the white background and a very small publisher view will work.

**Comment by msach22** [comment]
The `toggleCamera` function won't work because `publisher` is not defined. The publisher object is defined in the `initializeSession` method, but is not available outside of that scope. 
You can fix this by declaring publisher where you're declaring `apiKey`, `sessionId`, and `token`.

This is not a bug with the SDK.

**Comment by thereverendruby** [comment]
Oh I didn't mean it was a bug, it was more of a how can I access this :) Sorry for the confusion.

**Comment by msach22** [comment]
Thanks for clarifying @thereverendruby. Hope it's working for you.
