### ISSUE TITLE
Video element paused, auto-resuming warning when session & publisher are destroyed

### ISSUE THREAD

**Issue by davideberlein** [opentok/opentok-web-samples#106]
At the end of a video / voice call I call `publisher.destroy()` and `session.disconnect()` And I get the following warning:
```
Video element paused, auto-resuming. If you intended to do this, use publishVideo(false) or subscribeToVideo(false) instead.
```
I think this shouldn't happen, when we're destroying everything.

![image](https://user-images.githubusercontent.com/3438183/70619879-2f800a00-1c16-11ea-83be-a178f8887691.png)

**Comment by santhoshkumar-27** [comment]
Hi Opentok team, I'm using tokbox in my angular project, it works fine, but while ending the session I'm also encountering the same error, and the video red dot icons still on

**Comment by garyThrels** [comment]
Was there any actual response to this? @devwithzachary ?
