### ISSUE TITLE
opentok/client not working on mobile browsers

### ISSUE THREAD

**Issue by Moaz-Rashid** [opentok/opentok-web-samples#118]
Updated the sample angular app with the 2.17.0 package of opentok/client build and hosted he application;
On all mobile browsers the safari,chrome, firefox, only subscriber works but publisher fails to publish the video although the browser is allowed to access mic and camera of the device.

**Comment by kulttuuri** [comment]
I've noticed similar issue, not sure if this is related. Calling `Opentok.getUserMedia` function on **any** mobile device kills the video and shows that publisher took too long to publish. Removing call to `OpenTok.getUserMedia` solves the problem.

The reason I use `Opentok.getUserMedia` is to allow user to change their video / audio device while on the call. Currently even [all the examples on the Opentok website](https://tokbox.com/developer/guides/audio-video/js/#setAudioSource) about changing audio / video devices in web are dead.

Did you fix the issue by downgrading to older opentok client?

**Comment by DevVue** [comment]
Any updates on this i am facing a similar issue?
