### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by NatanTechofNY** [opentok/opentok-web-samples#128]
Getting the following error when using OpenTok JS SDK on a simple page. I have looked everywhere for an answer and have also tried changing versions but no luck.

`index.js:18 Uncaught TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at s (index.js:18)
    at index.js:57
    at new a (index.js:90)
    at e.exports (shorthandSelector.js:6)
    at Object.o.name.a.request (browser.js:52)
    at Object.o.name.a.post (browser.js:95)
    at analytics.js:23
    at e (QueueRunner.js:22)
    at e.t.run (QueueRunner.js:26)
    at e.t.add (QueueRunner.js:9)
    at analytics.js:21
    at e.exports.logEvent (analytics.js:136)
    at analytics.js:90
    at guid_storage.js:118
    at guid_storage.js:23
s @ index.js:18
(anonymous) @ index.js:57
a @ index.js:90
e.exports @ shorthandSelector.js:6
o.name.a.request @ browser.js:52
o.name.a.post @ browser.js:95
(anonymous) @ analytics.js:23
e @ QueueRunner.js:22
t.run @ QueueRunner.js:26
t.add @ QueueRunner.js:9
(anonymous) @ analytics.js:21
logEvent @ analytics.js:136
(anonymous) @ analytics.js:90
(anonymous) @ guid_storage.js:118
(anonymous) @ guid_storage.js:23
s.get @ guid_storage.js:96
t.logEvent @ analytics.js:80
logEvent @ index.js:535
logConfigurationFileEvent @ index.js:549
connect @ index.js:817
initializeSession @ xGksBHvv:210
(anonymous) @ xGksBHvv:235
`

**Comment by guillaumepotier** [comment]
Hi there. I had the exact same issue.

Currently, the only way I found was to patch opentok.js `selectorToElementArray` method by the following one:

```javascript
const selectorToElementArray = function selectorToElementArray(selector, context) {
  let elements;

  if (typeof selector === 'undefined') {
    return [];
  }

  if (typeof selector === 'string') {
    elements = [];
    const idSelector = idRegex.exec(selector);
    context = context || document;

    if (idSelector && idSelector[1]) {
      const element = context.getElementById(idSelector[1]);

      if (element) {
        elements.push(element);
      }
    } else {
      elements = context.querySelectorAll(selector);
    }
  } else if (
  		selector &&
  		(
  			(selector.upload && selector.send) || // here is my hacky condition to ensure we go here when XMLHttpRequest
  			selector.nodeType ||
  			(typeof window !== undefined ? window : global).XMLHttpRequest && selector instanceof (typeof window !== undefined ? window : global).XMLHttpRequest ||
  			selector === (typeof window !== undefined ? window : global)
  		)
  	) {
    // allow OTHelpers(DOMNode) and OTHelpers(xmlHttpRequest)
    elements = [selector];
    context = selector;
  } else if (Array.isArray(selector)) {
    elements = selector.slice();
    context = null;
  } else {
    elements = nodeListToArray(elements);
  }

  return elements;
}; // ElementCollection contains the result of calling OTHelpers.
//
```

Hope that helps
