### ISSUE TITLE
[Angular v5 + Ionic-Angular v3.9.8] Session not able to connect for production builds

### ISSUE THREAD

**Issue by vindrek** [opentok/opentok-web-samples#135]
I have an angular application which is able to establish session connection fine when I run it with dev mode (i.e. `ionic-app-scripts serve`). However, after I have built it for production (i.e. `ionic-app-scripts build --prod`), the session is no longer able to connect and I can see "Connecting" in the console, but never "Connected".

Bear in mind I use ionic only for UI components and build processes, so Angular sample project applies for my case. No cordova!

Relevant parts of my package.json:

```
{
  "scripts": {
    "serve": "node copy-env-config.js --env dev | ionic-app-scripts serve",
    "build:production": "node copy-env-config.js --env prod | ionic-app-scripts build --prod",
    "build:staging": "node copy-env-config.js --env staging | ionic-app-scripts build --prod"
  },
  "config": {
    "ionic_copy": "./config/copy.config.js",
    "ionic_uglifyjs": "./config/uglifyjs.config.js",
    "ionic_generate_source_map": "true"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@opentok/client": "2.17.1",
    "ionic-angular": "3.9.8",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/tsc-wrapped": "^4.4.6",
    "@ionic/app-scripts": "3.2.4",
    "rollup-plugin-replace": "^1.1.1",
    "tslint": "^5.4.3",
    "tslint-ionic-rules": "0.0.11",
    "typescript": "~2.6.2"
  },
  "engines": {
    "node": "7.5.0",
    "npm": "4.2.0"
  }
}
```

And tsconfig which matches [the one from the Ionic sample project](https://github.com/opentok/opentok-ionic-samples/blob/master/Basic-Video-Chat/tsconfig.json):

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "noStrictGenericChecks": true,
    "types": [],
    "skipLibCheck": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

All help is very much appreciated!

**Comment by uma-vijay** [comment]
I don't use ionic but I'm facing the same issue. Were you able to resolve the issue? Any help is much appreciated

**Comment by umadeviauriss** [comment]
If it might help anyone who bumps into this thread, I got it resolved using the following build command:
ng build --prod --aot=false --build-optimizer=false

**Comment by vindrek** [comment]
Hey. I was also able to get it working but it does not look pretty. To bypass the script being processed in the transpilation process, I simply import the opentok library statically in my index.html. But, obviously, this is not a real solution to this issue but a workaround.

**Comment by uma-vijay** [comment]
This way it worked for me too! But I have other processes I need to control when the streaming starts and stops... So this didn't suit my needs! Thanks a lot for letting me know! The build command mentioned above worked for me! If I come up with any other solution, I will definitely post it here!
