### ISSUE TITLE
why cycleVideo?

### ISSUE THREAD

**Issue by kaspesla** [opentok/opentok-web-samples#139]
Why isn't there a routine to set the camera directly? Cycling the cameras doesn't make a lot of sense on Desktop. I've never ever seen a website do it this way
You can set the mic directly. Is this an oversight?

Thanks,
Ken

**Comment by CTimmerman** [comment]
And even with multiple cameras, i'd like the cycle option to skip the webcam or have direct selection be as smooth.

**Comment by v-kpheng** [comment]
We have additional APIs that let you specify which camera to use, instead of having to cycle through them.  Please see https://tokbox.com/developer/guides/publish-stream/js/#set_camera_mic.

Closing.
