### ISSUE TITLE
Connect going into recursive loop

### ISSUE THREAD

**Issue by uma-vijay** [opentok/opentok-web-samples#140]
I'm facing a crazy problem when I deploy the Angular Basic Video Chat code provided here:
https://github.com/opentok/opentok-web-samples/tree/master/Angular-Basic-Video-Chat

This code work fine when I checked in my localhost
But when I deploy the same on a server I am not able to proceed beyond connect. After session.connect is called it throws me this error:
ERROR RangeError: Maximum call stack size exceeded

I'm confused as I'm able to get this running as is on my localhost but not on a server

I also tried the sample with plain html & javascript given here:
https://tokbox.com/developer/quickstart/
This works fine on the same server

Can anyone please guide me as to where the issue lies? I'm unable to nail the issue.

**Comment by umadeviauriss** [comment]
If it might help anyone who bumps into this thread, I got it resolved using the following build command:
ng build --prod --aot=false --build-optimizer=false

**Comment by MichaelJolley** [comment]
Thanks for sharing your fix @umadeviauriss!
