### ISSUE TITLE
Connect going into recursive loop After updating to "@opentok/client": "~2.17.4"

### ISSUE THREAD

**Issue by ahmad-ite** [opentok/opentok-web-samples#146]
Hi,
 I updated "**opentok/clien**t" library  to **"2.17.4"**
And I'm facing a problem when I deploy the Angular Basic Video.
error:
ERROR RangeError: Maximum call stack size exceeded
note :
this issue is founded before and closed  [issue140](https://github.com/opentok/opentok-web-samples/issues/140)
and I tried the same solution but It didn't solve

**Comment by developercodevian** [comment]
I'm also facing the same issue!

**Comment by developercodevian** [comment]
Even "ng build --prod --aot=false --build-optimizer=false" this command couldn't solve the issue.

**Comment by ahmad-ite** [comment]
Yes, I tried before, but the command couldn't solve the issue.

**Comment by developercodevian** [comment]
Yes, If you found a solution to this issue please let me know. Also, I'll inform you if I found something on this issue.

**Comment by ahmad-ite** [comment]
> Yes, If you found a solution to this issue please let me know. Also, I'll inform you if I found something on this issue.

Certainly

**Comment by yallen011** [comment]
Can you post your full log so that someone can review it?

**Comment by ahmad-ite** [comment]
Hi @yallen011 
this is the log error :

![Capture](https://user-images.githubusercontent.com/38505823/88021485-9798b600-cb3e-11ea-86bd-b1a2b5022f11.PNG)

**Comment by pritamnb** [comment]
Hey @ahmad-ite which Angular version are you using?

**Comment by ahmad-ite** [comment]
> Hey @ahmad-ite which Angular version are you using?

Hi I use angular 6

**Comment by pritamCodevian** [comment]
Hi, @ahmad-ite Please update your Angular version to 8. I was facing this issue on Angular 6 as well but when I update the angular CLI and core the issue is resolved. Please try updating your angular version.

**Comment by yallen011** [comment]
Hi @ahmad-ite, did @pritamCodevian solution solve your problem?

**Comment by pritamCodevian** [comment]
Hi @yallen011.
By upgrading the angular version solves the issue.

**Comment by yallen011** [comment]
yes, I was trying to get an affirmative from @ahmad-ite so that the issue could be resolved and closed.
