### ISSUE TITLE
Production error : Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by developercodevian** [opentok/opentok-web-samples#147]
Hello,

The issue is only on production. It's working superbly on the Local server.
I'm using Angular 6 for frontend and backend is using nodeJS. 

**Brief issue**
    When I tried to invoke initSession() which will then call opentok service to generate a room afterword the publisher window suppose to show up but it didn't. The console comes up with the "maximum call stack size exceeded" error.[
![image_2020_07_13T11_26_03_607Z](https://user-images.githubusercontent.com/56816510/87300209-1b451800-c52b-11ea-86ec-6729119284a1.png)
](url)

**Comment by yallen011** [comment]
duplicate of #146 @developercodevian please try updating to Angular v8 and see if this solves your error.

**Comment by developercodevian** [comment]
Yes it solves the issue.
