### ISSUE TITLE
No video source error when cycling video on Android 11 #726

### ISSUE THREAD

**Issue by kimuraz** [opentok/opentok-web-samples#171]
Opentok.js version: `2.18.4` 

When trying to use the `cycleVideo()` method, I get an error for devices using Android 11.

The error is shown on the print is thrown by a similar code as this one:

```js
         async switchCam() {
             if (publisher) {
                 try {
                     const newCamDevice = await publisher.cycleVideo();
                 } catch (err) {
                     console.error(err.message);
                 }
             }
         }
```

![image](https://user-images.githubusercontent.com/9062864/102516572-4bbb5000-408f-11eb-8702-a0b2341951fa.png)

Maybe related to: https://github.com/opentok/opentok-android-sdk-samples/issues/324

The same code works on:

* Motorola Z (android 9)
* Motorola Edge (android 10)
* Galaxy S10 (android 10)
* Xiaomi 9T (android 10)

The permissions were granted on all devices. It doesn't work on:
* Pixel 3a (android 11)
* Pixel 4a (android 11)

**Comment by janoonaj** [comment]
hello, it is closed? it still does not work in android 13
