### ISSUE TITLE
Publish video

### ISSUE THREAD

**Issue by gleborgne** [opentok/opentok-web-samples#179]
I follow the publish video sample. Locally I have the video and sound running well on the publisher, but people connected in the session have sound but no image showing. I tried using multiple mp4 videos with same results.

I'm running Chrome (Version 89.0.4389.82)

**Comment by gleborgne** [comment]
I was told by a representative of Vonage that this is bug in Chrome that should be fixed in Chrome 90. We fallback to rendering the video through a canvas.

**Comment by robinmonjo** [comment]
Thank you very much 😊. You spare me a night of digging !

**Comment by Abhishek304** [comment]
I am still getting this issue on latest chrome version i.e. 94.0.4606.61 (Official Build) (64-bit). Please confirm, if this issue has been fixed for you guys. We are getting 1500 error.

OT.exception :: title: Unable to Publish (1500) msg: ICEWorkflow
Session.publish :: Could not publish in a reasonable amount of time

**Comment by schacon** [comment]
I get a similar issue as the original post. It looks fine locally, but other subscribers only see what looks to be the yellow channel of the video. I can tell it's the same video, it's just almost all white and yellow and nothing else.

<img width="318" alt="shot2021-11-10-14 29 38" src="https://user-images.githubusercontent.com/70/141204210-9aad3a13-f29e-4a7a-9764-8a83e8e8eeef.png">

You can see the top here is a publishing source that's using the camera, the yellow box is the video that's coming in from the videoSource method. The code is basically exactly the Publish Video example here.

This is Chrome Version 95.0.4638.69 (Official Build) (x86_64)

**Comment by v-kpheng** [comment]
Closing, since quite a few releases of both Chrome and the JS SDK have been published since this issue was filed.  If still an issue, please file another ticket.  Thanks!
