### ISSUE TITLE
apply background filter to a video call

### ISSUE THREAD

**Issue by hamza-embelem** [opentok/opentok-web-samples#279]
I am using the opentok applyVideofilter. By default with type: 'backgroundBlur', it is working, but, when I am using the click event, it is publishing another client. is there a solution for this? Also , can i see the option on screen to enable and disable blur filter in background

**Comment by v-kpheng** [comment]
@hamza-embelem, the clicking issue is likely an application-level bug.  If you feel otherwise, can you post a jsfiddle please?

For blurring of screen share, this is only possible if you publish a custom stream.  Also, it requires the most recent version of the JS SDK.

Hope that helps!
