### ISSUE TITLE
OT.getDevices() get speakers

### ISSUE THREAD

**Issue by pdxbenjamin** [opentok/opentok-web-samples#333]
Is there a way for OT.getDevices() to get the attached speakers list?

**Comment by conshus** [comment]
Hi @pdxbenjamin.
`OT.getDevices()` is used to get a list of input devices.
To get a list of Audio Output Devices, please use `OT.getAudioOutputDevices()`
Here's more info: https://tokbox.com/developer/sdks/js/reference/OT.html#getAudioOutputDevices

Let me know if this answers your question.
Thanks.
