### ISSUE TITLE
Inbound Audio does not work with VOIP sample

### ISSUE THREAD

**Issue by trankin** [opentok/opentok-web-samples#335]
We've been using OpenTok with Connection Service for some time.  Working on updating to use > SDK 28 and are having some troubles with incoming audio on the Android side.  Outbound Audio and Video work fine, Inbound Video works fine, but inbound Audio does nothing.   

We tried re-working to use the Basic VoIP sample provided to see if some new permissions have changed or to see if we are missing something, but found that the VoIP sample also does not get inbound audio with a device running version 31 of the SDK.

Just looking to see if anyone has confirmed that it's working properly for them to see if we're barking up the wrong tree.

**Comment by trankin** [comment]
@devwithzachary, Hey, Yes I can confirm that the issue was with the Android samples only and not the web samples.. and interestingly, the issue was only with the VOIP sample.  

The solution was to update our Audio Driver to the latest version of the AdvancedAudioDriver used in this demo project.

https://github.com/nexmo-se/mobile-caller-demo-android

**Comment by devwithzachary** [comment]
Great news, glad you where able to get it solved :+1
