### ISSUE TITLE
MediaRecorder API sample

### ISSUE THREAD

**Issue by aullman** [opentok/opentok-web-samples#52]
We already have an [Archiving sample](https://github.com/opentok/opentok-web-samples/tree/master/Archiving) which shows you how to use the OpenTok Archiving API. But there is a new [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) available in some browsers that lets you record streams to your local machine. 👍 this if you would like to see a sample of how to do that with OpenTok. Similar to this one here https://webrtc.github.io/samples/src/content/getusermedia/record/

**Comment by aullman** [comment]
I wasn't working on it yet, I have registered your vote for it though. In the meantime the [StreamFilter sample](https://github.com/opentok/opentok-web-samples/tree/master/Stream-Filter) shows you how to get access to a MediaStream in opentok and the [WebRTC MediaRecorder sample](https://webrtc.github.io/samples/src/content/getusermedia/record/) shows you how to record a MediaStream.

**Comment by motoku** [comment]
Thank you @aullman ! 👍
