### ISSUE TITLE
[ts] Type '(err: any) => void' has no properties in common with type 'SubscriberProperties'. in subscriber.component.ts

### ISSUE THREAD

**Issue by PK1NONLY** [opentok/opentok-web-samples#57]
ngAfterViewInit() {
  
   
    const subscriber = this.session.subscribe(this.stream, this.subscriberDiv.nativeElement, (err) => {
      if (err) {
        alert(err.message);
      }
    });

   }

i didn't change anything from the sample code but its showing error as 
[ts] Type '(err: any) => void' has no properties in common with type 'SubscriberProperties'. in subscriber.component.ts in ngAfterViewInit Method on  **(err) =>** .

**Comment by msach22** [comment]
@PK1NONLY I'm assuming that you're talking about the Angular samples. We have a live web sample here: https://opentok.github.io/opentok-web-samples/Angular-Basic-Video-Chat/

Does that work for you?

**Comment by PK1NONLY** [comment]
@msach22 the live preview is working i tried installing the angular 5 sample code it is working but i am getting the above error also in vs code

**Comment by aullman** [comment]
Oh yeah, I get that error in vs code as well and it's right, the typescript definition is more strict about having to pass in the SubscriberOptions as the 3rd argument. Whereas the actual implementation is overloaded so that you can pass callback as the 3rd argument. I'll fix this.
