### ISSUE TITLE
The first window is not updating when second window is open.

### ISSUE THREAD

**Issue by sparity123** [opentok/opentok-web-samples#58]
I downloaded this code, and tested. When open second window with same url, the first window is not updating like demo. Is there any specific version in angular/tokbox to make it work?

**Comment by postalangel** [comment]
same with me. I was searching for a reliable solution pay-as-you-go based on webrtc, so hope opentok is more reliable than direct webrtc implementation

**Comment by mmubasher** [comment]
Similar issue with me. Adding a console.log in app.component.ts shows a new stream does gets created when a stream is subscribed but page does not gets updated. 
 
` ngOnInit () {  
 .
 .
 .` 
  `  this.session.on('streamCreated', (event) => {` 
  `  console.log('new stream added', ++i);` 
  `  this.streams.push(event.stream);` 
 `}); 
 .
 .
 .
}
`
outputs in console as 
`new stream added 1`
Is this related to Angular or Tokbox client  ? using Tokbox Client 2.13.0 , Angular 5 and Angular CLI 1.6.7

**Comment by aullman** [comment]
Ah yes, it looks like this happens if you provide an apiKey/sessionId/token in your config.ts instead of a backend service (which is what our automated tests are checking).

**Comment by aullman** [comment]
Weird, if I do a setTimeout before resolving the initSession Promise (instead of just returning Promise.resolve) then it works fine. I'm guessing that the way Angular's change detection hooks into promises isn't working properly in this case for some reason. 

Oh well, let's detectChanges manually.

**Comment by janevikj** [comment]
Got the same issue with the newest opentok.js version 2.14 
Why do we have to add manual change detection when using opentok with Angular(v 4.2.4)? This issue shouldn't be closed as there is no explanation for this bug.

**Comment by vidueirof** [comment]
Experimenting same issue, using changeDetectorRef for manually detect changes brokes the rest of my app after using it for the call.
