### ISSUE TITLE
Opentok client session not able to connect

### ISSUE THREAD

**Issue by mmubasher** [opentok/opentok-web-samples#61]
I downloaded this sample as is and it worked like a charm. Upon creating a new project using ```ng new myapp``` and placing the same module in my code as in this sample. Session does not gets created and session state stays as 'Connecting'

There are no errors or warnings reported. Session created listener never gets triggered. 

Environment Specs: 
```
Angular CLI: 1.7.3
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9 

@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```
Browser 
```
1. Chrome Version 65.0.3325.162 (Official Build) (64-bit)
2. Firefox Quantum 58.0.2 (64-bit)
```

**Comment by aullman** [comment]
Are you able to host the app somewhere so that I can try to debug it?

**Comment by mmubasher** [comment]
@aullman I figured it out. I had missed a character in the `token` string. It is quite sad that @opentok/client sdk does not provides any information about invalid token. I found an event log in http requests that showed client trying to connect with server but there were no errors or warnings logged in console. See this log snapshot ![Image of log capture showing connection attempt event log](https://content.screencast.com/users/mubasher.stella/folders/Jing/media/62b1ef02-c493-4312-a1c5-c54747cb59f4/console%20log%20capture%20for%20invalid%20API%20token.png) image. I have asked Opentok support to note this behaviour and if possible validate the credentials provided for Opentok API.
The issue is fixed now. Please close this ticket.
