### ISSUE TITLE
signal : how to get senders time and receivers time from tokBox ?

### ISSUE THREAD

**Issue by SidharthRamesh01** [opentok/opentok-web-samples#65]
# Angular4
    this.historyArray=[]
    this.opentokService.initSession().then((session: OT.Session) => {
      this.session = session;
      this.session.on('signal', (event) => {
        if(event.type=="signal:msg"){
        this. historyArray.push({msg:event.data,id:"history-received",time:this.now});
        console.log("Received Message"+event);
    console.log(this.historyArray);
        }else{
          this.historyArray.push({msg:event.data,id:"history-sent",time:this.now});
          console.log("Sent Message"+event);
    console.log(this.historyArray);
      }
      });
    })

//i am implementing in angular 4,currently generating time locally

**Comment by aullman** [comment]
There is no time stored in the signal event by default but you could store it in there yourself by sending the time along with the signal.
