### ISSUE TITLE
Video not streaming properly on chrome 66

### ISSUE THREAD

**Issue by shashankmds** [opentok/opentok-web-samples#66]
We are publishing videos through canvas, and since chrome 66, it has stopped working properly..
Even your sample is now broken.
Can you please help how we can fix this, as we can't ask all our users to go and disable chrome hardware acceleration.

**Comment by msach22** [comment]
@shashankmds This looks like an issue with Chrome 66. Our team has filed a bug with Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=819472

This should be fixed in Chrome 68
