### ISSUE TITLE
Duplicate client after disconnect and connect

### ISSUE THREAD

**Issue by armenhajian** [opentok/opentok-web-samples#69]
I'm using `Basic-Video-Chat` example for group video chat. (https://tokbox.com/developer/tutorials/web/basic-video-chat/)
There are 2 clients connected to a session.
After 1 client disconnects ( `session.disconnect()` ) and connects again with `initializeSession()`
I get 3 clients (1-st disconnected is exists yet).
The problem is that on `session.disconnect()` client doesn't removed from client list but on re-connection
it creates new client.
After refreshing page on disconnect it works as it should be, but I need a functionality to do re-initialization with code.

**Comment by armenhajian** [comment]
The problem was solved. 
Just prevent this subscriber listener on second initialization.
```
session.on('streamCreated', function(event) {
       session.subscribe(event.stream, 'subscriber', {
           insertMode: 'append',
           width: '100%',
           height: '100%'
       }, handleError);
   })
```

**Comment by brayanL** [comment]
@armenhajian I think your answer is not a solution, someone can help me I'm getting duplicated streams when I'm trying to rejoin the video conference. I'm calling to OTSession.disconnect() when my component is unmounted, but when the VideConference component is back, I have duplicated videos.
![image](https://user-images.githubusercontent.com/8359783/146090797-717c7593-3dd3-4351-a723-093cb5335642.png)
