### ISSUE TITLE
Opentok throws error with angular server side rendering

### ISSUE THREAD

**Issue by skbelalmd** [opentok/opentok-web-samples#77]
Using opentok with angular server side rendering throws following error.
ReferenceError: window is not defined.

Error origin : 
Exploring the code, I found that the error is originated from following function 

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

There are also other references to document, window and other browser specific components, that breaks the angular app if it is using server side rendering.

**Comment by skbelalmd** [comment]
It has been almost more than 6 months. Is this going to be resolved?

**Comment by aullman** [comment]
We're not currently planning to support angular server side rendering. I'm not sure how it would work anyway. Are you able to avoid trying to use opentok.js when doing server side rendering? It doesn't really make sense to render a Publisher or Subscriber on the server side right?
