### ISSUE TITLE
Publish Canvas is not in sync 

### ISSUE THREAD

**Issue by masudhossain** [opentok/opentok-web-samples#83]
Is there additional configurations needed to have https://github.com/opentok/opentok-web-samples/tree/master/Publish-Canvas work in sync when the user goes incognito? Because right now when a user opens the window in two locations, the canvas is not in sync.

**Comment by aullman** [comment]
The publisher is not being published into a session. It is just displaying your local publisher. So when you open up the app in multiple windows the publishers are not synchronised, they are independent. If you want to see it synchronised you will need to call `session.publish(publisher)` and then subscribe to the stream that is created on the other side.
