### ISSUE TITLE
Publishing timeout in Safari

### ISSUE THREAD

**Issue by lxhoan** [opentok/opentok-web-samples#84]
Hello,

I try Basic Video Chat example on Safari (11.1.2) and get:

```
Unhandled Promise Rejection: AbortError: The operation was aborted.
OpenTok:Publisher:error OT.Publisher.onPublishingTimeout +0ms
OpenTok:GlobalExceptionHandler:error OT.exception :: title: Unable to Publish (1500) msg: ICEWorkflow +0ms

OpenTok:Session:error 
1500 +0ms – "Session.publish :: Could not publish in a reasonable amount of time"
s {code: 1500, message: "Session.publish :: Could not publish in a reasonable amount of time", name: "OT_TIMEOUT", stack: "nt@https://static.opentok.com/v2/js/opentok.min.js…static.opentok.com/v2/js/opentok.min.js:23:118806"}
```

**Comment by lxhoan** [comment]
I track down to this error

```
Exception with thrown value: OperationError: Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
```

**Comment by lxhoan** [comment]
I upgraded Safari to 12.0.3 and the issue is gone. So assume that's the drawback of WebRTC in earlier safari versions.

close this

**Comment by SureshSc** [comment]
I am facing this issue with Chrome 

> browserName : Chrome
> browserVersion : 79.0.3945
> osName : Windows 8.0
> userAgent : Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36.

Does any one know how to fix this or how to catch this exception

**Comment by kaspesla** [comment]
Anyone figure this one out? At least how to catch this error on the webpage?

**Comment by whistlepunks** [comment]
I'm seeing this in FireFox 88.0.1 (64-bit), Win 10. all other browsers seem to manage fine
