### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by UpadhyayShubham** [opentok/opentok-web-samples#87]
I am trying to use a video URL from S3 bucket and whenever I try to execute the following code:

```
          var video = document.getElementById('publisherVideo');
          video.crossOrigin = 'anonymous';
          const stream = video.captureStream();
```

it give me the following error: 

> Uncaught DOMException: Failed to execute 'captureStream' on 'HTMLMediaElement': Cannot capture from element with cross-origin data.

Please tell me how to go about it. I cannot upload the videos to my EC2 server. I tried with one video and it worked but I want to get video from S3 and play it.

**Comment by aullman** [comment]
I'm not sure if you can do this with S3 but you will need to set the Access-Control-Allow-Origin Header.

This Stackoverflow post might help https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header

More information on CORS here https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
